### ISSUE TITLE
Need for new dockerfile - fullstack embedded app agent

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/dockerfiles#5]
We need to create a new Dockerfile that allows for builds with the following packages installed:

- mvn
- JDK 11
- Hugo (configurable?)
- Node (configurable?)
- Yarn

The configurable parts aren't necessary, just nice to haves as we evolve our build process. We could always create a patch to create a new version of the image to get specific versions in the future.

**Comment by autumnfound** [comment]
Should I take a crack at this? I can base it off of the hugo-node image and add the extra bits that we need to make this run. I don't forsee us compiling native images in the near future so we shouldn't need GraalVM as the Java package.

**Comment by autumnfound** [comment]
Agent mostly works, needs to have the Java home set though, I'll look into it and make a patch

**Comment by mbarbero** [comment]
which Jenkinsfile? did you try on your laptop with `docker run -it --rm   .... -- make compile`?

**Comment by autumnfound** [comment]
I'm trying this with the react-eclipsefdn-membership jenkinsfile. I tried it just now, as I didn't think of doing that before...ugh.

```
❯ docker run -it --rm eclipsefdn/stack-agent-test:latest /bin/sh `make compile`
mariadb uses an image, skipping
postgres uses an image, skipping
keycloak uses an image, skipping
nginx-proxy uses an image, skipping
Building www
Building api
/bin/sh: can't open 'mvn': No such file or directory
```

Getting a different error though.

**Comment by mbarbero** [comment]
I manage to reproduce locally. Current folder is a fresh clone of https://github.com/EclipseFdn/react-eclipsefdn-members/:

```bash
docker run -it --rm  -v "$(pwd):/home/jenkins" -e HOME=/home/jenkins -w /home/jenkins  eclipsefdn/stack-build-agent:latest /bin/sh -c "make compile"
mvn clean
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< org.eclipsefoundation:react-container >----------------
[INFO] Building react-container 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
....
```

2 things: 
* in https://github.com/EclipseFdn/dockerfiles/issues/5#issuecomment-854868787, you seem to use `eclipsefdn/stack-agent-test ` rather than `eclipsefdn/stack-build-agent`. I guess that `eclipsefdn/stack-agent-test` is a stale image you built locally for testing and that it does not contain maven.
* Also, for better compatibility with running on the build cluster, it is advised to change the `FROM alpine:3.13` of your Dockerfile to `FROM eclipsecbi/alpine:3.13` (though it does not change anything in this case).

**Comment by autumnfound** [comment]
We've done a successful build now, so I think we can close this! Thanks for your assistance in getting this going, its much appreciated!!
